UPDATE category SET name = 'Neque Sed Ltd', percent = 523, min_payment = 89 WHERE category_id = 1;
UPDATE category SET name = 'Donec Inc.', percent = 152, min_payment = 467 WHERE category_id = 2;
UPDATE category SET name = 'Cursus Corp.', percent = 177, min_payment = 955 WHERE category_id = 3;
UPDATE category SET name = 'Curabitur PC', percent = 858, min_payment = 108 WHERE category_id = 4;
UPDATE category SET name = 'Ac Turpis Incorporated', percent = 96, min_payment = 498 WHERE category_id = 5;
UPDATE category SET name = 'Etiam Ligula LLP', percent = 91, min_payment = 407 WHERE category_id = 6;
UPDATE category SET name = 'A Facilisis Non PC', percent = 652, min_payment = 212 WHERE category_id = 7;
UPDATE category SET name = 'Sagittis Felis Donec Consulting', percent = 342, min_payment = 150 WHERE category_id = 8;
UPDATE category SET name = 'Nunc Commodo Auctor LLC', percent = 250, min_payment = 760 WHERE category_id = 9;
UPDATE category SET name = 'Tempus Risus Ltd', percent = 129, min_payment = 548 WHERE category_id = 10;
UPDATE category SET name = 'Fermentum Metus LLP', percent = 590, min_payment = 18 WHERE category_id = 11;
UPDATE category SET name = 'Et Company', percent = 341, min_payment = 827 WHERE category_id = 12;
UPDATE category SET name = 'Sodales Purus Foundation', percent = 982, min_payment = 527 WHERE category_id = 13;
UPDATE category SET name = 'Ornare Placerat Corporation', percent = 426, min_payment = 909 WHERE category_id = 14;
UPDATE category SET name = 'Ligula Eu Enim Corp.', percent = 757, min_payment = 467 WHERE category_id = 15;
UPDATE category SET name = 'Cras Corp.', percent = 210, min_payment = 933 WHERE category_id = 16;
UPDATE category SET name = 'Nibh LLC', percent = 529, min_payment = 605 WHERE category_id = 17;
UPDATE category SET name = 'Penatibus Et Magnis Industries', percent = 96, min_payment = 790 WHERE category_id = 18;
UPDATE category SET name = 'Gravcategory_ida Nunc Sed LLC', percent = 92, min_payment = 373 WHERE category_id = 19;
UPDATE category SET name = 'Et Lacinia PC', percent = 350, min_payment = 905 WHERE category_id = 20;
UPDATE category SET name = 'Aliquam Foundation', percent = 784, min_payment = 556 WHERE category_id = 21;
UPDATE category SET name = 'Sit Amet Ornare Institute', percent = 387, min_payment = 338 WHERE category_id = 22;
UPDATE category SET name = 'Nec Associates', percent = 27, min_payment = 476 WHERE category_id = 23;
UPDATE category SET name = 'Mauris Eu Associates', percent = 449, min_payment = 719 WHERE category_id = 24;
UPDATE category SET name = 'At Corp.', percent = 845, min_payment = 420 WHERE category_id = 25;
UPDATE category SET name = 'Tellus Faucibus LLC', percent = 82, min_payment = 662 WHERE category_id = 26;
UPDATE category SET name = 'Pede Ultrices A Inc.', percent = 313, min_payment = 656 WHERE category_id = 27;
UPDATE category SET name = 'Tristique Ac LLC', percent = 173, min_payment = 10 WHERE category_id = 28;
UPDATE category SET name = 'Vehicula Pellentesque Tinccategory_idunt LLC', percent = 217, min_payment = 578 WHERE category_id = 29;
UPDATE category SET name = 'Purus Nullam Corp.', percent = 210, min_payment = 510 WHERE category_id = 30;
UPDATE category SET name = 'Dolor Sit Inc.', percent = 392, min_payment = 355 WHERE category_id = 31;
UPDATE category SET name = 'Nullam Scelerisque Neque PC', percent = 489, min_payment = 274 WHERE category_id = 32;
UPDATE category SET name = 'Ornare Fusce Inc.', percent = 844, min_payment = 967 WHERE category_id = 33;
UPDATE category SET name = 'Morbi Sit Corp.', percent = 158, min_payment = 685 WHERE category_id = 34;
UPDATE category SET name = 'Nibh Quisque Nonummy Inc.', percent = 849, min_payment = 357 WHERE category_id = 35;
UPDATE category SET name = 'Dolor Foundation', percent = 247, min_payment = 181 WHERE category_id = 36;
UPDATE category SET name = 'Sit Amet Diam LLP', percent = 912, min_payment = 924 WHERE category_id = 37;
UPDATE category SET name = 'Nec Corp.', percent = 890, min_payment = 569 WHERE category_id = 38;
UPDATE category SET name = 'Tinccategory_idunt Nibh Corp.', percent = 579, min_payment = 275 WHERE category_id = 39;
UPDATE category SET name = 'Eleifend Nunc PC', percent = 103, min_payment = 304 WHERE category_id = 40;
UPDATE category SET name = 'Magna Cras PC', percent = 38, min_payment = 288 WHERE category_id = 41;
UPDATE category SET name = 'Felis Eget Varius Ltd', percent = 240, min_payment = 906 WHERE category_id = 42;
UPDATE category SET name = 'Donec Elementum Lorem Foundation', percent = 167, min_payment = 458 WHERE category_id = 43;
UPDATE category SET name = 'Duis Risus Incorporated', percent = 884, min_payment = 35 WHERE category_id = 44;
UPDATE category SET name = 'A Feugiat Tellus Corp.', percent = 725, min_payment = 983 WHERE category_id = 45;
UPDATE category SET name = 'Arcu Imperdiet Ltd', percent = 729, min_payment = 635 WHERE category_id = 46;
UPDATE category SET name = 'Dui Incorporated', percent = 462, min_payment = 867 WHERE category_id = 47;
UPDATE category SET name = 'Egestas Fusce Ltd', percent = 413, min_payment = 671 WHERE category_id = 48;
UPDATE category SET name = 'In At Industries', percent = 982, min_payment = 469 WHERE category_id = 49;
UPDATE category SET name = 'Et Rutrum Non Limited', percent = 417, min_payment = 21 WHERE category_id = 50;