version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo_init:/docker-entrypoint-initdb.d/
    networks:
      hbd:
        ipv4_address: 172.16.0.2
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d/
      - ./scripts:/scripts
    networks:
      hbd:
        ipv4_address: 172.16.0.3
  airflow:
    image: apache/airflow:latest
    environment:

    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      hbd:
        ipv4_address: 172.16.0.4
networks:
  hbd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
