services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo_init:/docker-entrypoint-initdb.d/
    networks:
      hbd:
        ipv4_address: 172.16.0.2
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d/
      - ./scripts:/scripts
    networks:
      hbd:
        ipv4_address: 172.16.0.3
  api:
    build: source_service
    depends_on:
      - postgres
    networks:
      hbd:
        ipv4_address: 172.16.0.6
#  airflow-init:
#    image: apache/airflow:latest
#    entrypoint: "airflow db migrate"
#    volumes:
#      - ./etl/data/airflow.db:/opt/airflow/airflow.db
#    networks:
#      hbd:
#        ipv4_address: 172.16.0.5
  airflow:
#    depends_on:
#      - airflow-init
    build:
      context: ./etl
      dockerfile: Dockerfile-custom-airflow
    entrypoint: "airflow standalone"
    volumes:
      - ./etl/dags:/opt/airflow/dags
      - ./etl/data/airflow.db:/opt/airflow/airflow.db
    networks:
      hbd:
        ipv4_address: 172.16.0.4
networks:
  hbd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
