version: '3'
services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  service:
    build: .
    container_name: service
    depends_on:
      - database
    ports:
      - '8080:8080'
